/* eslint-disable import/no-anonymous-default-export */
const ADD_PLANTS = 'ADD_PLANTS'
const ADD_CURRENT_PLANT = 'ADD_CURRENT_PLANT'
const RESET_CURRENT_PLANT = 'RESET_CURRENT_PLANT'
const DELETE_PLANT = 'DELETE_PLANT'
const EDIT_PLANT = 'EDIT_PLANT'
const OPEN_MODAL = 'OPEN_MODAL'

export default {
  ADD_PLANTS,
  ADD_CURRENT_PLANT,
  RESET_CURRENT_PLANT,
  DELETE_PLANT,
  EDIT_PLANT,
  OPEN_MODAL
}
